### ISSUE TITLE
No longer maintained?

### ISSUE THREAD

**Issue by dpraul** [pirelenito/git-revision-webpack-plugin#46]
Hi @pirelenito, 

It's been nearly a year without any code movement in this repository. Is it still being maintained, or will you be seeking new maintainer(s)? There are some outstanding bugs in need of addressing.

**Comment by pirelenito** [comment]
Hi @dpraul ,

Indeed I haven't been updating this for awhile because it has functioning very well for the projects I've been building with it.

I'll be doing some housekeeping in the next following weeks to cleanup some old issues and hopefully update the project.

My goal was to try to eventually move it to https://github.com/webpack-contrib/ to give it a better home, but there is currently no process in place for that.

Thanks for using it and pinging me about the status! ❤️

**Comment by dpraul** [comment]
Thanks so much! Really appreciate the work you've done here.
